EcomPrototype/ViewModels/ProductListViewModel.cs
using EcomPrototype.DAL;
using EcomPrototype.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EcomPrototype.ViewModels
{
    public class ProductListViewModel
    {
        readonly EcomPrototypeContext dbContext = new EcomPrototype.DAL.EcomPrototypeContext();

        public List<Category> Categories { get; set; }
        public List<Product> Products { get; set; }
        public ProductListViewModel()
        {
            Categories = new List<Category>();
            Products = new List<Product>();
        }

        public void Build(List<Category> category, List<Product> products)
        {
            Categories = category;
            Products = products;
        }

    }
}

EcomPrototype/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.IO;
using EcomPrototype.Models;

namespace EcomPrototype.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Admin/Products
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Import()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ExecuteImport()
        {
          
            Integration.Products.Import();

            return RedirectToAction("Import");
        }


    }
}

EcomPrototype/Controllers/CartController.cs
using EcomPrototype.DAL;
using EcomPrototype.Models;
using EcomPrototype.ViewModels;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;

namespace EcomPrototype.Controllers
{
    [SessionState(SessionStateBehavior.Required)]
    public class CartController : Controller
    {
        EcomPrototypeContext dbContext = new EcomPrototypeContext();
        private string CartSessionKey = "EcomPrototype_Cart";
      
        public ActionResult Index()
        {
            Cart cart = GetCart();
            return View(cart);
        }

        public ActionResult CheckOut()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CheckOut(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                return View(customer);
            }

            return Confirmation(customer);
        }

        public ActionResult Confirmation(Customer customer)
        {
            var cart = GetCart();
            Order order = new Order(cart, customer);

            // Clear Cart
            
            var orderJson = JsonConvert.SerializeObject(order);
            using (WebClient client = new WebClient())
            {
                try
                {
                    string jsonStubUserKey = ConfigurationManager.AppSettings["JsonStubUserKey"];
                    string jsonStubProjectKey = ConfigurationManager.AppSettings["JsonStubProjectKey"];

                    client.Headers.Add("Content-Type", "application/json");
                    client.Headers.Add("JsonStub-User-Key", jsonStubUserKey);
                    client.Headers.Add("JsonStub-Project-Key", jsonStubProjectKey);

                    var result = client.UploadString(@"http://jsonstub.com/order", orderJson);
                    
                    var viewModel = new ConfirmationViewModel();
                    viewModel.OrderId = JObject.Parse(result)["orderId"].ToString();
                    viewModel.OrderJson = JsonConvert.SerializeObject(order);
                    SaveCart(new Cart());
                    return View(viewModel);
                }
                catch (Exception)
                {

                    throw;
                }
            }
        }

        public ActionResult Add(string articleNumber, int quantity)
        {
            if (quantity > 0)
            {
                var product = dbContext.Products.Where(a => a.ArticleNumber == articleNumber).SingleOrDefault();
                if (product != null)
                {
                    var cart = GetCart();
                    cart.Add(articleNumber, product.Price, product.Name, quantity);
                    SaveCart(cart);
                }
            }
            
            return Redirect(Request.UrlReferrer.ToString());
        }


        public ActionResult Update(string articleNumber,int quantity)
        {
            var cart = GetCart();

            var cartItem = cart.Items.Where(p => p.ArticleNumber == articleNumber).SingleOrDefault();
            if (cartItem != null)
            {
                if (quantity > 0) { 
                    cartItem.Quantity = quantity;
                } else
                {
                    cart.Items.Remove(cartItem);
                }
            }

            SaveCart(cart);

            return Redirect(Request.UrlReferrer.ToString());
        }


        public ActionResult Remove(string articleNumber)
        {
            var cart = GetCart();

            var cartItem = cart.Items.Where(p => p.ArticleNumber == articleNumber).SingleOrDefault();
            if (cartItem != null)
            {
                cart.Items.Remove(cartItem);            
            }

            SaveCart(cart);

            return Redirect(Request.UrlReferrer.ToString());
        }

        [ChildActionOnly]
        public ActionResult _MiniCart()
        {
            var viewModel = new CartViewModel();
            viewModel.Build(GetCart());
            return View(viewModel);
        }

        private Cart GetCart()
        {
            if (Session[CartSessionKey] == null)
                return new Cart();
            var cart = JsonConvert.DeserializeObject<Cart>(Session[CartSessionKey].ToString());
            return cart;
        }

        private void SaveCart(Cart cart)
        {
            JsonSerializer jsonSerializer = new JsonSerializer();
            Session[CartSessionKey] = JsonConvert.SerializeObject(cart);
        }

    }
}

EcomPrototype/Controllers/ProductsController.cs
using EcomPrototype.DAL;
using EcomPrototype.Models;
using EcomPrototype.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcomPrototype.Controllers
{
    public class ProductsController : Controller
    {
        private static EcomPrototypeContext dbContext = new EcomPrototypeContext();

        // GET: Products
        public ActionResult Index()
        {
            var viewModel = new ProductListViewModel();
            viewModel.Build(dbContext.Categories.ToList(), dbContext.Products.ToList());
            return View(viewModel);
        }

        public ActionResult Details(int id)
        {
            var product = dbContext.Products.SingleOrDefault(p => p.ArticleNumber == id.ToString());
            if (product == null)
                return HttpNotFound();
            return View(product);
        }

        public ActionResult Category(int? id)
        {
            var viewModel = new ProductListViewModel();
            if (id != null)
            {
                var category = dbContext.Categories.SingleOrDefault(c => c.Id == id);
                if (category == null)
                {
                    return HttpNotFound();
                }

                
                viewModel.Build(dbContext.Categories.ToList(), dbContext.Products.Where(p => p.Category.Id == category.Id).ToList());

                return View(viewModel);
            }
            else
            {
                viewModel.Build(dbContext.Categories.ToList(), dbContext.Products.ToList());
                return View("Index",viewModel);
            }
        }

        [ChildActionOnly]
        public PartialViewResult Product(Product product)
        {
            return PartialView("_Product",product);
        }

        [ChildActionOnly]
        public ViewResult Categories()
        {
            var categories = dbContext.Categories.ToList();
            return View("_Categories", categories);
        }

        //[ChildActionOnly]
        //public PartialViewResult Product(Product product)
        //{
        //    return PartialView("_Product",product);
        //}
    }
}

EcomPrototype/Views/Products/Category.cshtml
@model EcomPrototype.ViewModels.ProductListViewModel
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="grid-container">
    @{Html.RenderPartial("_ProductListWithCategories", Model);}
</div>

EcomPrototype/Views/Products/Details.cshtml
@model EcomPrototype.Models.Product
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="grid-container">
    @{Html.RenderPartial("_Product", Model);}
</div>

EcomPrototype/Views/Products/Index.cshtml
@model EcomPrototype.ViewModels.ProductListViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="grid-container">
    @{Html.RenderPartial("_ProductListWithCategories", Model);}
</div>

EcomPrototype/Views/Products/_Categories.cshtml
@model List<EcomPrototype.Models.Category>

<ul class="menu vertical">
    <li>@Html.ActionLink("Alla", "Index")</li>
    @foreach (var category in Model)
    {
    <li>@Html.ActionLink(category.Name,"Category",new { id = category.Id })</li>
    }

</ul>

EcomPrototype/Views/Products/_Product.cshtml
@model EcomPrototype.Models.Product

<h2>@Model.Name</h2>
<i>Art nr: @Model.ArticleNumber</i>
<div><img src="@Url.Content(Model.Image)" /></div>
<div>@Model.Price kr</div>
@using (Html.BeginForm("Add", "Cart", new { articleNumber = Model.ArticleNumber }))
{
    <div style="width:100%;clear:both;">
        <input type="text" id="quantity" name="quantity" value="1" style="float:left;width:35px;" /><button class="button" type="submit" style="float:left;margin-left:20px;">Lägg i kundvagn</button>
    </div>
}

EcomPrototype/Views/Products/_ProductList.cshtml
<div class="grid-x grid-margin-x" data-equalizer>

    @foreach (var product in Model)
    {

    <div class="cell large-3 small-8 product">
        <a href="/Products/Details/@product.ArticleNumber">
            <h3>@product.Name</h3>
            <div>
                <div data-equalizer-watch>
                    <img src="@product.Image" />
                </div>
            </div>
            <div class="price">@product.Price kr</div>
        </a>
        
        @using (Html.BeginForm("Add","Cart",new { articleNumber = product.ArticleNumber }))
        {
        <div style="width:100%;clear:both;">
            <input type="text" id="quantity" name="quantity" value="1" style="float:left;width:35px;" /><button class="button" type="submit" style="float:left;margin-left:20px;">Lägg i kundvagn</button>
        </div>
        }

    </div>

        }


</div>

EcomPrototype/Views/Products/_ProductListWithCategories.cshtml
@model EcomPrototype.ViewModels.ProductListViewModel


<div class="grid-x grid-margin-x">
    <div class="cell large-2">@{Html.RenderAction("Categories", Model.Categories);}</div>
    <div class="cell large-9">
        @{Html.RenderPartial("_ProductList", Model.Products);}
    </div>
</div>